// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixhgowdjvsntimdvmauz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4aGdvd2RqdnNudGltZHZtYXV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzk4MDQsImV4cCI6MjA2Njg1NTgwNH0.xW2ArYUAig9nTJwye11avRt_K3L-GW0XVbmWe0yxngc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});